spring:
  application:
    name: acl
  data:
    mongodb:
      uri: mongodb://diuser:diuser@localhost:27017/dataintegration
      database: dataintegration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/data-integration-realm

server:
  port: 8083

service:
  token-path: http://localhost:8080/realms/data-integration-realm/protocol/openid-connect/token
  legacy-system:
    client-id: legacy-system-api
    client-secret: RP38Ppn3y9DGT6FwYigkvKmZfzAQd2JR
    host: http://localhost:8084/api
