spring:
  application:
    name: data-integration-to-legacy-acl-api
  data:
    mongodb:
      uri: ${DATA_INTEGRATION_ACL_API_DB_URL}
      database: ${DATA_INTEGRATION_ACL_API_DATABASE}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

server:
  port: 8083

service:
  token-path: ${KEYCLOAK_TOKEN_PATH}
  legacy-system:
    client-id: ${LEGACY_SYSTEM_CLIENT_ID}
    client-secret: ${LEGACY_SYSTEM_CLIENT_SECRET}
    host: ${LEGACY_SYSTEM_HOST}
