spring:
  application:
    name: acl
  data:
    mongodb:
      uri: mongodb://diuser:diuser@localhost:27017/dataintegration
      database: dataintegration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/data-integration-realm

server:
  port: 8083
